require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - "bin/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "db/schema.rb"

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Style/Documentation:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 15

RSpec/NestedGroups:
  Max: 4
